version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      development-dependencies:
        patterns:
          - '@types/*'
          - '@typescript-eslint/*'
          - 'eslint*'
          - 'mocha'
          - 'typescript'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
